version: '3.8'
services:
  db:
    build:
      context: ./src/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: globant_books
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass)
    container_name: golang_db
    volumes:
      - db_mysql: /var/lib/mysql
    ports:
      - "3306:3306"
    networks: 
      - gostacknet
    tty: true
  app:
    build:
      context: ./src/app
    container_name: golang_app
    volumes:
      - "./go_app:/go"
    ports:
      - "8080:8080"
    networks: 
      - gostacknet
    tty: true
    restart: on-failure

volumes:
  go_app:
  db_mysql:

networks:
  gostacknet:
    driver: bridge